# Generated by Django 4.2.5 on 2023-09-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_website_companydetail_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='technology_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Technology_Name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='companydetail',
            old_name='City',
            new_name='city',
        ),
    ]
